# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: train
    displayName: Train model
    steps:
      - task: riserrad.azdo-databricks.azdo-databricks-configuredatabricks.configuredatabricks@0
        displayName: 'Configure Databricks Cluster'
        inputs:
          url: 'https://adb-5583552319182079.19.azuredatabricks.net/'
          token: dapi2f7f262521dcbc63be1f28570e89a496
      - task: riserrad.azdo-databricks.azdo-databricks-executenotebook.executenotebook@0
        displayName: Train
        inputs:
          notebookPath: /Shared/train
          existingClusterId: '0618-190813-trues609'
      - task: riserrad.azdo-databricks.azdo-databricks-waitexecution.waitexecution@0
        displayName: 'Wait for Notebook execution'
