# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build and Train model
  jobs:
  - job: train
    displayName: Train model
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.7.*
      inputs:
        versionSpec: 3.7.*
    - task: riserrad.azdo-databricks.azdo-databricks-configuredatabricks.configuredatabricks@0
      displayName: 'Configure Databricks Cluster'
      inputs:
        url: $(databricks-url)
        token: $(databricks-token)
    - task: riserrad.azdo-databricks.azdo-databricks-executenotebook.executenotebook@0
      displayName: Train
      inputs:
        notebookPath: /Shared/train
        existingClusterId: $(databricks-cluster-id)
    - task: riserrad.azdo-databricks.azdo-databricks-waitexecution.waitexecution@0
      displayName: 'Wait for Training notebook'
    - task: riserrad.azdo-databricks.azdo-databricks-executenotebook.executenotebook@0
      displayName: Unit tests
      inputs:
        notebookPath: /Shared/tests
        existingClusterId: $(databricks-cluster-id)
    - task: riserrad.azdo-databricks.azdo-databricks-waitexecution.waitexecution@0
      displayName: 'Wait for Unit Tests'
- stage: Build Image
  jobs:
  - job: image
    displayName: Create and package model image
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.7.*
      inputs:
        versionSpec: 3.7.*
    - task: riserrad.azdo-databricks.azdo-databricks-configuredatabricks.configuredatabricks@0
      displayName: 'Configure Databricks Cluster'
      inputs:
        url: $(databricks-url)
        token: $(databricks-token)
    - task: riserrad.azdo-databricks.azdo-databricks-executenotebook.executenotebook@0
      displayName: Train
      inputs:
        notebookPath: /Shared/build-image
        existingClusterId: $(databricks-cluster-id)
    - task: riserrad.azdo-databricks.azdo-databricks-waitexecution.waitexecution@0
      displayName: 'Wait for Build image notebook'
- stage: Deploy to Dev
  jobs:
  - job: deploy-aci
    displayName: Deploy to Dev
    steps:
    - task: UsePythonVersion@0
      displayName: Use Python 3.7.*
      inputs:
        versionSpec: 3.7.*
    - task: riserrad.azdo-databricks.azdo-databricks-configuredatabricks.configuredatabricks@0
      displayName: 'Configure Databricks Cluster'
      inputs:
        url: $(databricks-url)
        token: $(databricks-token)
    - task: riserrad.azdo-databricks.azdo-databricks-executenotebook.executenotebook@0
      displayName: Deploy to ACI
      inputs:
        notebookPath: /Shared/deploy
        existingClusterId: $(databricks-cluster-id)
    - task: riserrad.azdo-databricks.azdo-databricks-waitexecution.waitexecution@0
      displayName: 'Wait for Build image notebook'
